EBIvariation/eva-submission

etc/eva_project_validation.yaml
eva_submission/biosamples_submission.py
eva_submission/eload_brokering.py
eva_submission/eload_validation.py
tests/test_eload_brokering.py
tests/test_submit_to_bsd.py

Fix the skipping of BioSamples brokering which did not work when BioSample ids were already submitted.
Also remove validation of phone number (not always a string).

EVA-2281 - Fix brokering (again)

---

bin/broker_submission.py
eva_submission/ENA_submission/upload_to_ENA.py
eva_submission/ENA_submission/xlsx_to_ENA_xml.py
eva_submission/biosamples_submission.py
eva_submission/eload_brokering.py
eva_submission/eload_submission.py
eva_submission/eload_validation.py
tests/resources/eloads/ELOAD_4/.ELOAD_4_config.yml
tests/test_eload_brokering.py
tests/test_upload_to_ENA.py

Add report for brokering to be more consistent with the validation step
Couple of fixes to ENA XML generation and parsing identified while running in production

EVA-2321 - Brokering report

---

.github/workflows/python-package.yml
eva_submission/ENA_submission/xlsx_to_ENA_xml.py
tests/test_xlsx_to_xml.py

Most of the changes are test added

EVA-2322 - Add support for default hold date

---

eva_submission/eload_ingestion.py
eva_submission/ingestion_templates.py
nextflow/accession.nf
nextflow/variant_load.nf
tests/nextflow-tests/bin/fake_bcftools.sh

Various fixes to ensure ingestion automation works end-to-end in the cluster.

EVA-2355 - Dev run of ingestion automation

---

bin/prepare_submission.py
eva_submission/eload_submission.py
tests/test_eload_submission.py

Override metadata using parameter from the command line in `prepare_submission.py`

EVA-2320 - Set taxid and reference genome from command line

---

nextflow/accession.nf
nextflow/variant_load.nf
tests/nextflow-tests/java/FakeAccessionPipeline.java

* Ensure new properties file (rather than appending) using `newWriter`
* Remove uncompressed vcfs before copying to FTP

EVA-2409 - resolve remaining issues from ingestion run

---

eva_submission/eload_brokering.py
eva_submission/eload_ingestion.py
eva_submission/eload_submission.py
nextflow/accession.nf
tests/resources/eloads/ELOAD_33/.ELOAD_33_config.yml
tests/test_eload_brokering.py

Note that the csi index isn't being brokered but should be made available on our FTP, so I've opted to have the brokering automation communicate the file to ingestion automation via `20_scratch` and the eload config for now at least.

Make submitted vcf files + indices public, fix copy to ftp step for human studies

---

eva_submission/ENA_submission/upload_to_ENA.py
tests/test_XLSWriter.py
tests/test_eload_submission.py
tests/test_submit_to_bsd.py
tests/test_upload_to_ENA.py

Also a couple minor test improvements.

EVA-2455 - Store multiple analysis accessions in brokering config

---

bin/prepare_backlog_study.py
eva_submission/eload_backlog.py
eva_submission/eload_utils.py
eva_submission/submission_config.py
tests/test_eload_backlog.py
tests/test_eload_utils.py

- Add ability to force replacing the config (previous one is backup)
- Retrieve the reference accession from the analysis in metadata database
- Retrieve files from ENA when not available locally
- Support for multiple files per analysis

EVA-2465 - Improvement to prepare backlog 

---

eva_submission/eload_submission.py
eva_submission/eload_validation.py
eva_submission/samples_checker.py
tests/test_eload_submission.py

EVA-2459 - Check concordance between files and metadata

---

eva_submission/xlsx/xlsx_parser.py
eva_submission/xlsx/xlsx_parser_eva.py
tests/test_XLSReader.py

Born out of frustration of waiting for large excel spreadsheet to be parsed

Speed up of excel reader.

---

eva_submission/eload_ingestion.py

Fixes issue running ingestion for ELOAD_806

only get hold date if we're about to accession and make files public

---

eva_submission/eload_backlog.py
eva_submission/eload_ingestion.py
eva_submission/eload_submission.py
eva_submission/eload_utils.py
requirements.txt
tests/test_eload_backlog.py
tests/test_eload_ingestion.py

To be merged after [this PR](https://github.com/EBIvariation/eva-common-pyutils/pull/20) is merged and deployed.

EVA-2448 - Use updated database credential methods in pyutils

---

eva_submission/eload_utils.py
tests/test_eload_backlog.py

Fixes issue found in ELOAD-420.

Store hold date in config as a datetime object

---

.github/workflows/python-package.yml
bin/prepare_submission.py
eva_submission/ENA_submission/upload_to_ENA.py
eva_submission/eload_backlog.py
eva_submission/eload_preparation.py
eva_submission/eload_utils.py
eva_submission/nextflow/accession.nf
eva_submission/submission_config.py
eva_submission/xlsx/xlsx_parser.py
eva_submission/xlsx/xlsx_parser_eva.py
tests/nextflow-tests/run_tests.sh
tests/nextflow-tests/run_tests_human.sh
tests/nextflow-tests/test_ingestion_config.yaml
tests/nextflow-tests/test_ingestion_config_human.yaml
tests/nextflow-tests/vcf_files_to_ingest.csv
tests/resources/eloads/ELOAD_55/original_config.yml
tests/test_XLSWriter.py
tests/test_eload_backlog.py
tests/test_eload_config.py
tests/test_eload_submission.py
tests/test_eload_utils.py
tests/test_upload_to_ENA.py

Check VCF base name and not full path
Reset version when running `prepare_submission.py`

Multiple fixes for v1.0

---

.github/workflows/python-package.yml
bin/validate_submission.py
eva_submission/eload_ingestion.py
eva_submission/eload_submission.py
eva_submission/eload_utils.py
eva_submission/eload_validation.py
eva_submission/nextflow/validation.nf
eva_submission/nextflow/variant_load.nf
requirements.txt
tests/nextflow-tests/bin/fake_assembly_checker.sh
tests/nextflow-tests/bin/fake_vcf_validator.sh
tests/nextflow-tests/run_tests_validation.sh
tests/nextflow-tests/test_ingestion_config.yaml
tests/nextflow-tests/test_ingestion_config_human.yaml
tests/nextflow-tests/test_validation_config.yaml
tests/nextflow-tests/vcf_files_to_validate.csv
tests/resources/eloads/ELOAD_2/.ELOAD_2_config.yml
tests/test_eload_validation.py

Detect merge type and horizontally merge in validation rather than ingestion.
Also added a test for validation nextflow and removed the deprecated `validExitStatus` because I thought I would be modifying that nextflow code more... it has nothing to do with this ticket but I left it in anyway.

EVA-2366 - Detect and horizontally merge in validation

---

eva_submission/ENA_submission/xlsx_to_ENA_xml.py
tests/test_xlsx_to_xml.py

After checking with the [project XSD](http://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/ENA.project.xsd) we were missing an XML tag in the project/analysis links

Fix links for project and analysis

---

eva_submission/eload_validation.py
tests/test_eload_validation.py

Depends on [eva-vcf-merge](https://github.com/EBIvariation/eva-vcf-merge/pull/4).  Incremental diff with EVA-2366 [here](https://github.com/apriltuesday/eva-submission/compare/EVA-2366...apriltuesday:EVA-2501).

EVA-2501 - Vertical concatenation in submission automation

---

eva_submission/eload_backlog.py
tests/test_eload_backlog.py

Add missing entries in brokering

Add config entries to backlog

---

bin/ingest_submission.py
bin/provision_variant_warehouse_database.py
eva_submission/eload_ingestion.py
eva_submission/eload_utils.py
requirements.txt
tests/resources/submission_config.yml
tests/test_eload_ingestion.py

Consistently get the variant warehouse database name from the metadata or constructed from the taxonomy/assembly
Create the database in mongodb when it does not exist.

EVA-2308 - create variant warehouse database

---

bin/prepare_backlog_study.py
eva_submission/eload_backlog.py
eva_submission/eload_brokering.py
eva_submission/eload_ingestion.py
eva_submission/eload_submission.py

Add ability to pass an ELoadConfig object between object to have them share the same state

Ability to share EloadConfig

---

eva_submission/ENA_submission/upload_to_ENA.py
eva_submission/ENA_submission/xlsx_to_ENA_xml.py
tests/test_xlsx_to_xml.py

When brokering to an existing project the project_file does not exist 
So we should not upload it.

Fix brokering to existing project

---

eva_submission/eload_ingestion.py
tests/test_eload_ingestion.py
tests/test_vep_utils.py

This is to help detect and understand projects that are not showing up in the API

Warning when the browsable files are different from analysis files

---

eva_submission/eload_preparation.py
eva_submission/eload_submission.py
requirements.txt
tests/test_eload_submission.py

Added the function for logging file as well as the a function in the test

Adding logging file with the eload object

---

eva_submission/eload_ingestion.py
eva_submission/ingestion_templates.py
requirements.txt
tests/test_eload_ingestion.py

Merge after EBIvariation/eva-common-pyutils#25 and eva-commmon-pyutils version is updated to 0.3.20

Include count service credentials in accession properties file

---

bin/prepare_backlog_study.py
eva_submission/eload_backlog.py
eva_submission/eload_utils.py
eva_submission/ingestion_templates.py
eva_submission/vep_utils.py
tests/test_eload_backlog.py
tests/test_vep_utils.py

Change the way the VEP cache is extracted to ensure the finale directory name is the `species_name`
Add --keep_config option in prepare_backlog_study.py
Fix SQL queries

Fix VEP extraction & other fixes

---

bin/broker_submission.py
bin/ingest_submission.py
bin/migrate_submission.py
bin/prepare_backlog_study.py
bin/prepare_submission.py
bin/update_metadata_post_ingestion.py
bin/upgrade_config.py
bin/validate_submission.py
eva_submission/eload_submission.py
eva_submission/submission_config.py
tests/test_eload_submission.py

Switch the writing of config file to be explicit using the context manager

Write config using context manager

---

bin/broker_submission.py
eva_submission/ENA_submission/upload_to_ENA.py
eva_submission/ENA_submission/xlsx_to_ENA_xml.py
eva_submission/eload_brokering.py
tests/resources/submission_config.yml
tests/test_upload_to_ENA.py
tests/test_xlsx_to_xml.py

This PR is on the back of PR https://github.com/EBIvariation/eva-submission/pull/109

EVA-2871 - Async ena upload

---

bin/prepare_backlog_study.py
eva_submission/eload_backlog.py
eva_submission/eload_brokering.py
eva_submission/vep_utils.py
tests/test_eload_backlog.py

Ensure that the VCF files are in the submission folder then run the brokering preparation to ensure the files and config are properly set for ingestion

EVA-2931 - Use brokering prep instead of emulating it

---

eva_submission/submission_qc_checks.py

Catch HTTP exceptions and report FTP connection failure accurately

EVA-2764 - Fix QC report

---

bin/ingest_submission.py
eva_submission/eload_ingestion.py
requirements.txt

Add specific instance for clustering and default to 6
add missing accessioning import properties
Add missing output folder for export step.

EVA-3183 - V1.10 fixes

---

.github/workflows/python-package.yml
eva_submission/eload_ingestion.py
eva_submission/nextflow/accession.nf
eva_submission/nextflow/migrate.nf
eva_submission/nextflow/prepare_brokering.nf
eva_submission/nextflow/validation.nf
eva_submission/nextflow/variant_load.nf
tests/nextflow-tests/test_ingestion_config.yaml
tests/nextflow-tests/test_ingestion_config_human.yaml

Also prevent accession load process from running for human studies.

EVA-3209 - Convert remaining pipelines to DSL2

---

eva_submission/eload_ingestion.py

Small fixes after real-world testing uncovered some issues

EVA-3208 - Fix typo in SQL and adjust behavior when Ensembl cannot resolve taxonomy

---

eva_submission/ENA_submission/xlsx_to_ENA_xml.py
eva_submission/eload_utils.py
eva_submission/xlsx/xlsx_validation.py

This would allow the single sequence to be brokered. 
It does not address how the single sequence would be ingested into EVAPRO or the impact on accessioning.

Pass single sequence accession to ENA

---

eva-submission-docker/postgres_docker/metadata.sql

Includes changes necessary for a study to be returned by web services and show up in website, as well as changes to support displaying DOI in addition to PMID for publications.

EVA-3462: Update metadata db docker image

---

eva_submission/submission_qc_checks.py
tests/test_submission_qc.py

This PR comes after #196 
You can get a diff between the two [here](https://github.com/tcezard/eva-submission/compare/fix/annot_and_stats...tcezard:eva-submission:fix/qc_submission)

Add support for the split steps in variant_load when QC a submissions

---

eva_submission/ENA_submission/upload_to_ENA.py
tests/test_upload_to_ENA.py

Fix parsing of JSON from ENA async endpoint as documented in https://ena-docs.readthedocs.io/en/latest/submit/general-guide/programmatic.html#asynchronous-endpoint

Fix Async upload to ENA

---

eva_submission/nextflow/accession_and_load.nf
eva_submission/submission_qc_checks.py
tests/resources/eloads/ELOAD_103/.ELOAD_103_config.yml
tests/resources/projects/PRJEB33333/00_logs/GCA_000003205.1_eva_remapped.vcf_ingestion.log
tests/resources/projects/PRJEB33333/00_logs/GCA_000003205.1_vcf_extractor.log
tests/resources/projects/PRJEB33333/00_logs/GCA_000247795.2_backpropagate_to_GCA_000003205.1.log
tests/resources/projects/PRJEB33333/00_logs/accessioning.test2.vcf.gz.log
tests/resources/projects/PRJEB33333/00_logs/pipeline.test2.vcf.gz.log
tests/test_submission_qc.py

Also refactor submission_qc_check.py

EVA-3650 - Run new statistic calculation step

---

eva_submission/etc/eva_project_validation.yaml

Same regex as for project links

Add regex for analysis links

---

eva_sub_cli_processing/sub_cli_to_eload_converter/json_to_xlsx_converter.py
eva_submission/eload_preparation.py
requirements.txt
tests/test_eload_preparation.py

I might need a new version of eva-sub-cli to be released before the test can pass.

EVA-3756 - Convert the new spreadsheet to v1.1.4

---

bin/delete_submission.py
bin/submission_status.py
eva_submission/eload_deletion.py
eva_submission/qc_utils.py
eva_submission/submission_qc_checks.py
tests/test_submission_deletion.py
tests/test_submission_qc.py

This should also resolve [EVA-3741](https://embl.atlassian.net/browse/EVA-3741)

EVA-3772: Add QC results to config and check before deletion

---

eva_submission/ena_retrieval.py
eva_submission/evapro/table.py
eva_submission/steps/structural_variant_detection.py
eva_submission/vep_utils.py

Not so important ... but this should silence warning that are thrown out during the test execution

Address warnings brought up during the tests

---

eva_submission/biosample_submission/biosamples_submitters.py
tests/test_biosamples_submission.py

Change the collection date property to not have underscore when submitting to BioSamples

Sample "collection_date" to "collection date"

---

eva_submission/evapro/populate_evapro.py

Not sure why this was not raised before but it seems to prevent execution without it ...

Wrap literal query with text() function
