eva_submission/eload_ingestion.py
eva_submission/ingestion_templates.py
nextflow/accession.nf
nextflow/prepare_brokering.nf
nextflow/validation.nf
nextflow/variant_load.nf
tests/nextflow-tests/bin/fake_bcftools.sh
tests/nextflow-tests/bin/fake_bgzip.sh
tests/nextflow-tests/clean_tests.sh
tests/nextflow-tests/test_ingestion_config.yaml
tests/nextflow-tests/test_ingestion_nextflow.sh
tests/test_eload_ingestion.py
tests/test_xlsx_to_xml.py
tests/test_xlsx_validation.py

* Merging VCFs moved to Nextflow, so now will happen in the cluster
* Properties files creation moved to Nextflow,  allows Nextflow to control more parts of the pipeline.  (I think this should actually let us run accessioning and variant load in parallel since they both just rely on the validated VCFs, but for now I haven't implemented that.)
* Also made Nextflow indentation consistent with documentation and made some other fixes.

EVA-2331 - Merge VCFs and write properties files in nextflow

---

eva_submission/eload_utils.py
nextflow/accession.nf

This is the workaround discussed in the development meeting.  Skipped structural variants are treated as a success, but other types of skipped variants will still be treated as a failure.
Also modified mongo credentials method to ensure it fetches the primary host from the [current settings file](https://github.com/EBIvariation/configuration/blob/master/eva-maven-settings.xml#L111).

EVA-2409 - treat skipped structural variants as a success in accessioning

---

bin/genome_downloader.py
eva_submission/eload_backlog.py
eva_submission/eload_submission.py
eva_submission/eload_utils.py
requirements.txt
tests/resources/submission_config.yml
tests/test_eload_backlog.py
tests/test_eload_submission.py

This only adds support for the download of single reference sequence.
Because it does not have any assembly report some of the validation steps are not working.

EVA-2364 - Add single reference sequences  support

---

bin/prepare_backlog_study.py
eva_submission/eload_backlog.py

Fixes to backlog automation found while running [ELOAD-506](https://www.ebi.ac.uk/panda/jira/browse/ELOAD-506).
* Use public date from ENA if no hold date
* Output a report so user can confirm analysis/assembly details
The issue of suppressed analysis is postponed to [EVA-2442](https://www.ebi.ac.uk/panda/jira/browse/EVA-2442).

Backlog automation fixes

---

bin/broker_submission.py
bin/check_samples_eva.py
bin/detect_submission.py
bin/genome_downloader.py
bin/ingest_submission.py
bin/prepare_backlog_study.py
bin/prepare_submission.py
bin/validate_submission.py
eva_submission/eload_brokering.py
eva_submission/eload_validation.py
setup.py

Also fix a bug in validation report and genome downloader
Scripts will be executable after deployment with [deploy_python_in_venv.sh](https://github.com/EBIvariation/eva-tools/pull/111/files)

EVA-2451 Make scripts in bin executable

---

eva_submission/ingestion_templates.py

Use secondaryPreferred reads in Mongo 4.0 environment for both accessioning and ingestion pipelines

EVA-2445 - Use secondaryPreferred reads in Mongo 4.0 environment

---

eva_submission/eload_ingestion.py
eva_submission/eload_validation.py
requirements.txt
tests/test_eload_validation.py

Also implemented removing nextflow work directory during the ingestion automation, as an easy space-saving measure.

EVA-2560 - Check analysis alias collisions during validation

---

eva_submission/eload_ingestion.py
eva_submission/ingestion_templates.py
eva_submission/nextflow/variant_load.nf
tests/nextflow-tests/test_ingestion_config.yaml
tests/nextflow-tests/test_ingestion_config_human.yaml

* Reinstate merge during ingestion for backwards compatibility (compare [this commit](https://github.com/apriltuesday/eva-submission/commit/b5d2a29942d6ef3e80a1b176e8114beedc125228))
* Follow vcf path symlinks to ensure Spring resumes jobs appropriately
* Add property for variant load pipeline to avoid an exception after Spring upgrade (this was added to the accessioning properties but missed for variant load)

EVA-2580 - Fixes for variant load

---

bin/ingest_submission.py
bin/prepare_backlog_study.py
bin/update_metadata_post_ingestion.py
eva_submission/eload_backlog.py
eva_submission/eload_ingestion.py
eva_submission/eload_validation.py
eva_submission/ingestion_templates.py
eva_submission/nextflow/variant_load.nf
eva_submission/vep_utils.py
tests/nextflow-tests/vcf_files_to_ingest.csv
tests/resources/eloads/ELOAD_33/.ELOAD_33_config.yml
tests/test_eload_ingestion.py
tests/test_vep_utils.py

This also means that the VEP species is analysis specific. 
This PR also add: 
- a function to load assembly_set_id which is sometime missing
- the ability to merge VCF files during backlog preparation
- a new script that only runs queries on the metadata database

EVA-2603 - Download VEP cache base on assembly instead of taxonomy

---

eva_submission/eload_brokering.py

Prevent restarting the brokering preparation when it has already been performed
This must have been broken when we switched to multiple analysis

Fix brokering prep

---

bin/ingest_submission.py
eva_submission/eload_ingestion.py
eva_submission/nextflow/variant_load.nf
tests/nextflow-tests/test_ingestion_config.yaml
tests/nextflow-tests/test_ingestion_config_human.yaml
tests/resources/settings.xml
tests/resources/submission_config.yml
tests/test_eload_ingestion.py

* Include `resume` parameter in ingestion, which is passed to Nextflow; any functionality in Python will be re-run
* Refactor `eload_ingestion` to consolidate Nextflow management
* Refactor tests in a futile attempt to improve readability
* Remove merge step from `variant_load`, as it's no longer needed and interferes with Nextflow resumption
(Previous draft version is in a [branch](https://github.com/apriltuesday/eva-submission/tree/ingestion-resume), just in case.)

EVA-2404 - Resumable ingestion

---

eva_submission/eload_validation.py
tests/resources/validations/multiple_synonyms_text_assembly_report.txt
tests/test_eload_validation.py
tests/test_vep_utils.py

When multiple synonymous contigs are in the report the assembly checker cannot validate the results. This is now reported accurately by the validation.

Add check for presence of multiple contig synonyms in the report

---

.github/workflows/python-package.yml
eva_submission/ENA_submission/xlsx_to_ENA_xml.py
eva_submission/eload_brokering.py
eva_submission/eload_ingestion.py
eva_submission/eload_submission.py
tests/test_eload_brokering.py
tests/test_eload_ingestion.py

Add support for metadata load of the analysis present in the config based on the existing_project in the config
In brokering switch around the propagation of existing project from command line to spreadsheet to config so that the existing project could be set by the spreadsheet directly and still be reported.

EVA-2846 - Metadata load for existing project

---

eva_submission/biosamples_submission.py
eva_submission/eload_brokering.py
eva_submission/eload_ingestion.py
tests/test_submit_to_bsd.py

This PR brings a new class that can update All provided BioSamples accession with an external reference to the EVA study page.
Also add the ability to authenticate to BioSamples via ENA webin credentials
All updates are done via curation objects rather than edits to the original object

EVA-2693 Update BioSamples

---

eva_submission/ENA_submission/upload_to_ENA.py
eva_submission/ENA_submission/xlsx_to_ENA_xml.py
eva_submission/eload_brokering.py
tests/test_xlsx_to_xml.py

When submitting multiple analysis to the same project through several submissions the scond would work because it would use the Project as alias then the third would not because it would also use the existing project as alias. This replace the Alias with the ELOAD number.

When submitting to existing project create alias based on ELOAD

---

tests/test_eload_preparation.py

This is a weird one, see failure on gitlab [here](https://gitlab.ebi.ac.uk/EBIvariation/eva-submission/-/jobs/1139172) - basically one of the preparation tests is trying to download `GCA_000001405.1` instead of just the specified sequence and consequently running out of space, I think this should fix it but it's quite strange.

Fix gitlab tests

---

.github/workflows/python-package.yml
README.md
eva_submission/eload_ingestion.py
eva_submission/nextflow/accession.nf
eva_submission/nextflow/remap_and_cluster.nf
requirements.txt
tests/nextflow-tests/bin/fake_custom_assembly.py
tests/nextflow-tests/bin/fake_genome_downloader.py
tests/nextflow-tests/bin/fake_remapping_pipeline.nf
tests/nextflow-tests/build_tests.sh
tests/nextflow-tests/java/FakeClusteringPipeline.java
tests/nextflow-tests/java/FakeRemappingExtractionPipeline.java
tests/nextflow-tests/java/FakeRemappingLoadingPipeline.java
tests/nextflow-tests/run_tests_clustering.sh
tests/nextflow-tests/test_ingestion_config.yaml
tests/resources/settings.xml
tests/resources/submission_config.yml
tests/test_eload_ingestion.py

The nextflow pipeline should look very similar to the one from eva-tools, just modified to run the remapping processes for multiple source assemblies if present in the project.
Also I think `eload_ingestion.py` is in need of a bit of a refactor, but that's for another time...

EVA-2904 - Add remapping and clustering to ingestion automation

---

eva_submission/nextflow/accession.nf
eva_submission/nextflow/variant_load.nf
tests/nextflow-tests/vcf_files_to_ingest.csv

Set full path in nextflow test to make sure they are used as full path in the accession and variant load
Change the path to val to keep the original path

Fix Nextflow paths

---

bin/retrieve_archives_from_lts.py
bin/submission_status.py
eva_submission/eload_status.py
eva_submission/eload_submission.py
eva_submission/retrieve_eload_and_project_from_lts.py
requirements.txt

New script that provide a status of an ELOAD based on the content of the config, metadata database variant and accession warehouses

EVA-3316 - Detect ELOAD status

---

bin/broker_submission.py
eva_submission/ENA_submission/upload_to_ENA.py
eva_submission/ENA_submission/xlsx_to_ENA_xml.py
eva_submission/biosamples_submission.py
eva_submission/eload_ingestion.py
eva_submission/eload_preparation.py
eva_submission/eload_submission.py
eva_submission/eload_utils.py
eva_submission/eload_validation.py
eva_submission/submission_qc_checks.py
tests/test_eload_ingestion.py
tests/test_eload_preparation.py
tests/test_eload_utils.py
tests/test_eload_validation.py

- I had one case of submission to ENA that came back with no poll link which crashed the process fixed in https://github.com/EBIvariation/eva-submission/commit/cef6a6a8b562a76334d035a8515fa3b8e1385479
- Fix QC submission check stating that FTP files are missing in https://github.com/EBIvariation/eva-submission/commit/9564594897b3c1e831f6f7fd2791f43c19b699a2
- Novel attribute often comes with extra white spaces in them: fix this in https://github.com/EBIvariation/eva-submission/commit/0e4b405867ab31e71fc203222b5dd76c64d09b56
- Make the sure Project and Analysis alias are unique with the Webin account:  https://github.com/EBIvariation/eva-submission/commit/87277c66e4aed1fdf3c65617fe8526609d446f8e
- Check that the project exists in EVAPRO before loading from ENA if it does only load the …

Fixes from submissions

---

eva_submission/eload_preparation.py
eva_submission/eload_submission.py
eva_submission/eload_validation.py
eva_submission/nextflow/prepare_brokering.nf
tests/test_vep_utils.py

* Prepare submission shouldn't write unique aliases to metadata spreadsheet
* ENA brokering _should_ write unique aliases
* Flag for normalisation to warn on reference check issues rather than fail
* Test updates for Ensembl 110

Fixes from submission processing

---

eva_submission/nextflow/prepare_brokering.nf

This statement was useful when normalisation was during the validation. Now it's only obfuscating the process.

Do not catch error during normalisation.

---

eva_submission/ENA_submission/xlsx_to_ENA_xml.py
tests/test_xlsx_to_xml.py

When submitting to an existing project accession manually created the submission alias has often been used already
This allow the submission alias to still be unique when a project was manually created using the ELOAD id

Submit to existing project accession

---

bin/check_sample_exist.py
bin/modify_existing_sample.py
eva_submission/biosample_submission/biosamples_communicators.py
eva_submission/biosample_submission/biosamples_submitters.py
eva_submission/biosamples_submission.py
eva_submission/eload_brokering.py
eva_submission/xlsx/xlsx_validation.py
tests/test_biosamples_submission.py
tests/test_eload_brokering.py
tests/test_eload_validation.py

This PR change the process for BioSample creation and update.
The `biosample_submission.py` can now create a new BioSample, overwrite and existing one, add a curation object on top of an existing one, or create a derived sample from an existing one.
The brokering only allows to Create new BioSample or use existing one as is
A new script should be used to update existing Biosamples
Validation identify existing BioSample missing collection date or geographic location.

EVA-3471: Update Biosamples with creation/update process

---

eva_submission/nextflow/remap_and_cluster.nf

Retrieve the VCF file with the taxonomy id included. 
This should be backward compatible

EVA-3308 - extract VCF file with taxonomy id

---

eva_submission/eload_ingestion.py
eva_submission/nextflow/accession_and_load.nf
tests/test_eload_ingestion.py
tests/test_vep_utils.py

Split the variant load nextflow process into 
1. variant load 
2. annotation run
3. statistics calculation
Also remove the option to run annotation only.

EVA-3457 - Split variant load

---

eva_submission/nextflow/accession_and_load.nf

Should wait for all accessioning steps to finish before running accession load (fixes issue in ELOAD_1268)

Wait for all accessioning steps before loading accessions

---

README.md
bin/ingest_submission.py
eva_submission/eload_ingestion.py
eva_submission/nextflow/accession_and_load.nf
eva_submission/vep_utils.py
requirements.txt
tests/nextflow-tests/run_tests_clustering.sh
tests/nextflow-tests/run_tests_remapping_clustering.sh
tests/nextflow-tests/test_ingestion_config_variant_load.yaml
tests/nextflow-tests/test_ingestion_no_remapping_config.yaml
tests/test_eload_ingestion.py
tests/test_vep_utils.py

Test should pass when a new version of eva-common-pyutils is released

Remove instance id from accessioning and clustering

---

eva_submission/eload_submission.py
eva_submission/eload_validation.py
eva_submission/nextflow/validation.nf
eva_submission/steps/detect_contigs_naming_convention.py
eva_submission/steps/rename_contigs_from_insdc_in_assembly.py
requirements.txt
tests/resources/eloads/ELOAD_2/.ELOAD_2_config.yml
tests/test_detect_naming_conventions.py
tests/test_eload_validation.py

Add a new validation that always succeeds. 
It should check and retrieve the naming convention use in each VCF file and summarise it in the config

EVA-3604 - Add naming convention check

---

eva_submission/eload_brokering.py
eva_submission/eload_ingestion.py
tests/test_eload_ingestion.py

And other improvement to the error reporting

EVA-3641 Specify the analysis only option correctly

---

eva_submission/nextflow/accession_and_load.nf

Test the number of missing variants in the accessioning in relation to the number of report SVs after removing duplicates.

Allow accession to complete when there are SV duplicates in the source file

---

eva_submission/nextflow/accession_and_load.nf

After [EVA-3721](https://www.ebi.ac.uk/panda/jira/browse/EVA-3721) this restriction is no longer needed.

Remove maxForks restriction in accessioning

---

eva_submission/etc/eva_project_conf.yaml
eva_submission/xlsx/xlsx_validation.py
requirements.txt
tests/test_xlsx_validation.py

- When searching for a GCA and it returns multiple assembly (because the search is done on text match), select the GCA that was used for the search. 
- Compare taxonomy vs scientific name using the scientific name from Ensembl or NCBI.

Few fixes from prod

---

eva_sub_cli_processing/sub_cli_to_eload_converter/sub_cli_to_eload_converter.py
eva_submission/eload_preparation.py
eva_submission/eload_submission.py
eva_submission/eload_utils.py
eva_submission/eload_validation.py
eva_submission/nextflow/validation.nf
eva_submission/samples_checker.py
tests/nextflow-tests/bin/fake_eva_sub_cli.py
tests/nextflow-tests/run_tests_validation.sh
tests/nextflow-tests/test_validation_config.yaml
tests/test_eload_preparation.py
tests/test_eload_validation.py
tests/test_sub_cli_processing/test_sub_cli_to_eload_converter.py

Also replaces all references to "File type" with checks on the file extension.
Implementation notes:
* eva-sub-cli only runs if metadata JSON is present - so for CLI submissions or email submissions using the new spreadsheet. In these cases the prepare script will update the JSON and add its location to the ELOAD config.
* It does not have its own validation task, this means it runs if and only if the validation Nextflow runs (and JSON exists)
* Does not have a pass/fail state and so doesn't block anything if it fails or doesn't run, obviously can't be forced either
* Appears at the bottom of the validation report as "Did not run", failed to run or a link to the HTML report in the validations folder
* Runs **shallow** validation
* Requires two additions to the submission config, the …

EVA-3694 - Run eva-sub-cli as part of validation

---

eva_submission/eload_ingestion.py
eva_submission/evapro/populate_evapro.py

This what we said we should not do but on the other hand it is a very easy fix.

Retrieve the taxonomy from the config when not in the ENA project
